import { DocumentData } from "../types/common.types";
// Force refresh

export interface ExtractionData {
  field: string;
  value: string;
  evidence: string;
  clause: string;
}

export const DUMMY_DOCUMENTS: DocumentData[] = [
  {
    id: "doc_1",
    name: "Commercial_Lease_Prestige_Towers.pdf",
    uploadedAt: "2024-05-10",
    status: "ready",
    size: "2.4 MB",
  },
  {
    id: "doc_2",
    name: "Office_Space_Agreement_City_Centre.pdf",
    uploadedAt: "2024-05-12",
    status: "processing",
    size: "1.8 MB",
  },
  {
    id: "doc_3",
    name: "Warehouse_Lease_Ind_Area.pdf",
    uploadedAt: "2024-05-08",
    status: "failed",
    size: "3.1 MB",
  },
  {
    id: "doc_4",
    name: "Retail_Store_Main_Street.pdf",
    uploadedAt: "2024-05-14",
    status: "ready",
    size: "1.2 MB",
  },
  {
    id: "doc_5",
    name: "Co_Working_Space_Agreement.pdf",
    uploadedAt: "2024-05-15",
    status: "ready",
    size: "0.9 MB",
  },
     {
    id: "doc_6",
    name: "Industrial_Plot_Lease.pdf",
    uploadedAt: "2024-05-16",
    status: "ready",
    size: "4.5 MB",
  },
   {
    id: "doc_7",
    name: "Sublease_Agreement_Annex.pdf",
    uploadedAt: "2024-05-17",
    status: "ready",
    size: "1.1 MB",
  },
];

export const DUMMY_EXTRACTIONS: Record<string, ExtractionData[]> = {
  "doc_1": [
    { field: "Lease Term", value: "Five (5) years commencing from Effective Date", evidence: "The lease term shall be for a period of five (5) years...", clause: "1.2" },
    { field: "Base Rent", value: "INR 2,00,000 per month", evidence: "Tenant agrees to pay substantial rent of INR 2,00,000...", clause: "2.1" },
    { field: "Security Deposit", value: "INR 12,00,000", evidence: "Security deposit equivalent to 6 months rent...", clause: "3.4" },
    { field: "Termination Notice", value: "3 Months", evidence: "Either party may terminate with 3 months prior notice...", clause: "9.1" },
    { field: "Subletting Allowed", value: "Yes", evidence: "Tenant may sublet with prior written consent...", clause: "7.3" },
  ],
  "doc_4": [
    { field: "Lease Term", value: "Three (3) years", evidence: "Valid for 3 years from signing...", clause: "1.1" },
    { field: "Base Rent", value: "INR 50,000 per month", evidence: "Monthly rental of INR 50,000...", clause: "2.0" },
     { field: "Security Deposit", value: "INR 2,00,000", evidence: "Refundable deposit of INR 2.0 Lakhs...", clause: "3.1" },
  ]
};

// export const INITIAL_KEYWORDS = [
//   "Premises Address", "Premises Floor/Unit", "Premises Area (Sq Ft)", "Premises Area (Sq M)", "Premises Type (Retail/Office/Industrial)", "Premises Plan/Exhibit Ref", "Property Name", "Property Type", "Property Owner / Landlord Legal Name", "Landlord Company Registration Number", "Landlord Contact Person", "Landlord Contact Email", "Landlord Contact Phone", "Tenant Legal Name", "Tenant Trading Name", "Tenant Company Registration Number", "Tenant Contact Person", "Tenant Contact Email", "Tenant Contact Phone", "Guarantor Name (if any)", "Guarantor Contact Details", "Property Manager Name", "Property Manager Contact", "Lease Execution Date", "Lease Effective Date", "Lease Commencement Date", "Rent Commencement Date", "Lease Expiry Date", "Lease Term (Years)", "Lease Term (Months)", "Initial Possession Date", "Possession Condition", "Commencement Conditions", "Option Exercise Deadline Dates", "Rent Free Period Start Date", "Rent Free Period End Date", "Prorated Rent Start", "Early Termination Notice Date", "Number of Renewal Options", "Renewal Option Term Length (Years)", "Renewal Notice Period (Days)", "Renewal Rent Calculation Method", "Right of First Refusal (Y/N)", "Right of First Refusal Description", "Right of First Offer (Y/N)", "Right of First Offer Description", "Expansion Option Details", "Expansion Space Area", "Relocation Rights (Y/N)", "Relocation Rights Description", "Relocation Compensation Terms", "Base Rent (Per Month)", "Base Rent Currency", "Base Rent (Annual)", "Base Rent Frequency", "Rent Payment Method", "Rent Account / Bank Details", "Rent Escalation Type (CPI/Fixed/% etc.)", "Escalation Start Date", "Escalation Frequency", "Escalation Rate (%)", "Escalation Cap (%)", "Escalation Floor (%)", "Escalation Calculation Formula", "CPI Index Source", "CPI Base Index Value", "CPI Base Index Date", "CPI Rounding Rules", "Market Rent Review Frequency", "Market Rent Review Methodology", "Benchmark Market Rent Source", "CAM Charges (Annual Estimate)", "CAM Recovery Type (Actual/Fixed/Cap)", "CAM Budget Year", "CAM Reconciliation Frequency", "CAM Reconciliation Due Date", "CAM Recoverable Items - List", "CAM Non-Recoverable Items - List", "CAM Base Year", "Gross-Up Clause (Y/N)", "CAM Cap (%)", "Management Fee Included in CAM", "Management Fee", "Management Fee Included in CAM (Y/N)", "Insurance Included in CAM (Y/N)", "Real estate Tax paymet method", "Real estate Tax paymet method description", "Utilities Included in CAM (Y/N)", "CAM Payment Frequency", "CAM Billing Address", "Supporting Docs Required for CAM", "Audit Rights for CAM (Y/N)", "Audit Rights for CAM & Audit Period (years)", "Property Tax Responsibility", "Property Tax Base Year", "Property Tax Apportionment Method", "Tax Appeals Responsibility", "VAT / GST Treatment of Rent", "Withholding Tax Responsibility", "Utilities Responsibility (Tenant/Landlord)", "Utilities Metering (Submeter Required)", "Electricity Meter ID", "Water Meter ID", "Gas Meter ID", "Utility Billing Frequency", "Utility Allocation Method", "Utility Transfer Date", "Utility Security Deposit Amount", "Utilities Metering (Submeter Restriction)", "Security Deposit Required", "Security Deposit Interest Payable (Y/N)", "Security Deposit Refund (Timeline)", "Bank Guarantee Amount", "Bank Guarantee Expiry Date", "Security Deposit Refund Description", "Letter of Credit Details", "Escrow Agent (if any)", "Guarantee Name (if guarantor)", "Guarantee Type", "Guarantee Expiry Date", "Personal Guarantee (Y/N)", "Guarantee Notice Period for call", "Guarantee Limit", "Invoice Requirements / Supporting Docs", "Invoice Delivery Method", "Invoice Address", "Late Payment Interest Rate (%)", "Late Payment Grace Period (Definition)", "Late Fee Fixed Amount", "Default Interest Calculation Method", "Payment Allocation Priority (Rent/CAM/Tax/Other)", "Payment Currency Conversion Terms", "Payment Day Cut-off Time", "Bank Charges Responsibility", "Electronic Funds Transfer Details Required per Lease?", "Electronic Funds Transfer Details Non-Compliance Fee?", "Electronic Funds Transfer Details Non-Compliance Fee Amount", "Electronic Funds Transfer Details Non-Compliance Description", "Foundation/Building/Exterior Responsibility", "Electrical and Lighting Systems Responsibility", "Electrical and Lighting Systems Responsibility Description", "Fire / Life Safety Responsibility", "Fire / Life Safety Responsibility Description", "Plumbing Responsibility", "Plumbing Responsibility Description", "Driveways, Walkways and Sidewalks Responsibility", "Driveways, Walkways and Sidewalks Responsibility Description", "Landscaping, Sweeping and Snow / Ice Responsibility", "Landscaping, Sweeping and Snow / Ice Responsibility Description", "Equipments Responsibility", "Equipments Responsibility Description", "Dock, Dock Equipment, and Dock Doors Responsibility", "Dock, Dock Equipment, and Dock Doors Responsibility Description", "Security Services Responsibility", "Security Services Responsibility Description", "Other Interior Responsibility", "Other Interior Responsibility Description", "Janitorial Services Responsibility", "Janitorial Services Responsibility Description", "Responsibilities - Roof", "HVAC Responsibility", "After-hours HVAC Charges", "Service Level Agreement (SLA) - Response Times", "Pest Control Responsibility", "Tenant Improvement Allowance Amount", "Tenant Improvement Allowance Amount Description", "TI Allowance Payment method", "TI Allowance Payment method Description", "TI Amortization (if applicable)", "Ownership of Improvements on Expiry", "Removal of Tenant Fixtures on Expiry", "Removal of Tenant Fixtures on Expiry Description", "Landlord Consent Required for Alterations", "Landlord Consent Required for Alterations Description", "Alterations Deposit", "Alterations Deposit Description", "Building Code Compliance for Alterations", "Punchlist Completion Requirements", "As-built Drawings Required (Y/N)", "Insurance - Tenant Minimum Coverage (Type & Limit)", "Insurance - Landlord Minimum Coverage (Type & Limit)", "Additional Insured Requirements", "Waiver of Subrogation (Y/N)", "Loss Payee Details", "Insurance Policy Renewal Notice Period", "Insurance Deductible Amount", "Casualty - Partial Damage Rent Abatement Terms", "Casualty - Total Destruction Termination Right (Y/N)", "Temporary Relocation Obligations", "Business Interruption Rent Suspension Terms", "Condemnation - Termination Rights", "Condemnation Termination Rights Description", "Assignment Permission", "Assignment Consent Process", "Consent Not to be Unreasonably Withheld", "Assignment Fee amount", "Assignment Fee Description", "Permitted Transferees / Assignment Conditions", "Subletting Permission", "Subletting Consent Process", "Sublease Rent Sharing Terms", "Subletting Fee amount", "Subletting Fee Description", "Permitted Use", "Prohibited Uses", "Radius / Non-Compete Clauses", "Hazardous Materials Prohibition", "Hazardous Materials Prohibition Description", "Signage Rights & Restrictions", "Signage Approval Required", "Signage Responsibility", "Tenant - Licenses Required for Operation", "Tenant - Responsible for Obtaining Licenses (Y/N)", "Occupancy Permit / Certificate of Compliance", "Certificate of Occupancy Date", "Health & Safety Requirements", "Fire Safety Certificates Required (Y/N)", "Events of Default - Tenant", "Events of Default - Landlord", "Cure Period for Tenant Default (days)", "Cure Period for Landlord Default (days)", "Remedies on Landlord Default", "Rent Acceleration Clause (Y/N)", "Distress Rights (Y/N)", "Mitigation Obligations on Termination", "Governing Law / Jurisdiction", "Dispute Resolution Mechanism (Arbitration/Court)", "Arbitration Institution", "Arbitration Seat / Venue", "Arbitration Rules Reference", "Limitation of Liability Clause Summary", "Waiver of Consequential Damages (Y/N)", "Force Majeure Clause Summary", "Survival Clauses List", "Severability Clause (Y/N)", "Entire Agreement Clause (Y/N)", "Amendments Must be in Writing (Y/N)", "Counterparts & Electronic Signatures (Y/N)", "Notice Address - Landlord", "Notice Address - Tenant", "Notice Method (Email/Registered Mail)", "Day-to-Day Building Manager Contact", "Emergency 24/7 Contact Number", "Operating Expense Statement Frequency (Reconcilation statement)", "Financial Statements Required (Y/N)", "Financial Statements Required timeline", "Financial Statements Required Description", "Audit Rights", "Access for Inspections (notice required?)", "Makegood / Dilapidations Standard", "Surrender Conditions", "Holdover Rent Rate (if tenant holds over)", "Holdover Period Treatment", "Break Clause Present (Y/N)", "Break Notice Period", "Break Fee Amount", "Conditions to Exercise Break Clause", "Access Hours to Premises", "24/7 Access (Y/N)", "Landlord Right to Access", "Tenant Right to Quiet Enjoyment", "Lockout Conditions", "Remediation Responsibility", "Environmental Indemnity Terms", "Asbestos / Lead Paint Disclosure", "Environmental Compliance Certificates Required", "Sustainability / ESG Obligations", "Energy Performance Required (Y/N)", "Green Building Certification (LEED/BREEAM) Requirements", "Energy Efficiency requirements", "Recycling Requirements", "Water Saving Measures Required", "Building Services Hours (HVAC/Lighting)", "Loading Bay Scheduling Process", "Deliveries / Receiving Hours", "Parking allocated area", "Parking allocated area description", "Parking allocated area restriction", "Parking area Responsibility", "Parking area Responsibility Description", "Water Resposibility", "Water Resposibility Description"
// ];
export const INITIAL_KEYWORDS = [
  "Premises Address",
  "Premises Floor/Unit",
  "Premises Area (Sq Ft)",
  "Premises Plan/Exhibit Ref",
  "Property Owner / Landlord Legal Name",
  "Tenant Legal Name",
  "Tenant Trading Name",
  "Tenant Contact Person",
  "Tenant Contact Email",
  "Tenant Contact Phone",
  "Guarantor Name (if any)",
  "Lease Effective Date",
  "Lease Commencement Date",
  "Rent Commencement Date",
  "Lease Expiry Date",
  "Lease Term (Years)",
  "Lease Term (Months)",
  "Initial Possession Date",
  "Rent Free Period Start Date",
  "Rent Free Period End Date",
  "Prorated Rent Start",
  "Early Termination Notice Date",
  "Number of Renewal Options",
  "Right of First Refusal (Y/N)",
  "Right of First Refusal Description",
  "Right of First Offer (Y/N)",
  "Right of First Offer Description",
  "Expansion Space Area",
  "Relocation Rights (Y/N)",
  "Relocation Rights Description",
  "Relocation Compensation Terms",
  "Rent Escalation Type (CPI/Fixed/% etc.)",
  "Escalation Rate (%)",
  "Escalation Cap (%)",
  "CPI Index Source",
  "CPI Base Index Value",
  "Market Rent Review Frequency",
  "Market Rent Review Methodology",
  "CAM Charges (Annual Estimate)",
  "CAM Reconciliation Frequency",
  "CAM Reconciliation Due Date",
  "CAM Recoverable Items - List",
  "CAM Non-Recoverable Items - List",
  "CAM Base Year",
  "Gross-Up Clause (Y/N)",
  "CAM Cap (%)",
  "Management Fee Included in CAM",
  "Management Fee",
  "Management Fee Included in CAM (Y/N)",
  "Insurance Included in CAM (Y/N)",
  "Real estate Tax paymet method",
  "Real estate Tax paymet method description",
  "Utilities Included in CAM (Y/N)",
  "Audit Rights for CAM (Y/N)",
  "Audit Rights for CAM & Audit Period (years)",
  "Tax Appeals Responsibility",
  "Utilities Responsibility (Tenant/Landlord)",
  "Utilities Metering (Submeter Required)",
  "Utilities Metering (Submeter Restriction)",
  "Security Deposit Required",
  "Security Deposit Interest Payable (Y/N)",
  "Security Deposit Refund (Timeline)",
  "Security Deposit Refund Description",
  "Letter of Credit Details",
  "Guarantee Name (if guarantor)",
  "Guarantee Type",
  "Late Payment Interest Rate (%)",
  "Late Payment Grace Period (Definition)",
  "Electronic Funds Transfer Details Required per Lease?",
  "Electronic Funds Transfer Details Non-Compliance Fee?",
  "Electronic Funds Transfer Details Non-Compliance Fee Amount",
  "Electronic Funds Transfer Details Non-Compliance Description",
  "Foundation/Building/Exterior Responsibility",
  "Foundation/Building/Exterior Responsibility Description",
  "Electrical and Lighting Systems Responsibility",
  "Electrical and Lighting Systems Responsibility Description",
  "Fire / Life Safety Responsibility",
  "Fire / Life Safety Responsibility Description",
  "Plumbing Responsibility",
  "Plumbing Responsibility Description",
  "Driveways, Walkways and Sidewalks Responsibility",
  "Driveways, Walkways and Sidewalks Responsibility Description",
  "Landscaping, Sweeping and Snow / Ice Responsibility",
  "Landscaping, Sweeping and Snow / Ice Responsibility Description",
  "Equipments Responsibility",
  "Equipments Responsibility Description",
  "Dock, Dock Equipment, and Dock Doors Responsibility",
  "Dock, Dock Equipment, and Dock Doors Responsibility Description",
  "Security Services Responsibility",
  "Security Services Responsibility Description",
  "Other Interior Responsibility",
  "Other Interior Responsibility Description",
  "Janitorial Services Responsibility",
  "Janitorial Services Responsibility Description",
  "Responsibilities - Roof",
  "Responsibilities - Roof Description",
  "HVAC Responsibility",
  "After-hours HVAC Charges",
  "Pest Control Responsibility",
  "Tenant Improvement Allowance Amount",
  "Tenant Improvement Allowance Amount Description",
  "TI Allowance Payment method",
  "TI Allowance Payment method Description",
  "TI Amortization (if applicable)",
  "Removal of Tenant Fixtures on Expiry",
  "Removal of Tenant Fixtures on Expiry Description",
  "Landlord Consent Required for Alterations",
  "Landlord Consent Required for Alterations Description",
  "Alterations Deposit",
  "Alterations Deposit Description",
  "Insurance - Tenant Minimum Coverage (Type & Limit)",
  "Additional Insured Requirements",
  "Waiver of Subrogation (Y/N)",
  "Casualty - Partial Damage Rent Abatement Terms",
  "Casualty - Total Destruction Termination Right (Y/N)",
  "Condemnation - Termination Rights",
  "Condemnation Termination Rights Description",
  "Assignment Permission",
  "Assignment Consent Process",
  "Consent Not to be Unreasonably Withheld",
  "Assignment Fee amount",
  "Assignment Fee Description",
  "Permitted Transferees / Assignment Conditions",
  "Subletting Permission",
  "Subletting Consent Process",
  "Sublease Rent Sharing Terms",
  "Subletting Fee amount",
  "Subletting Fee Description",
  "Permitted Use",
  "Prohibited Uses",
  "Hazardous Materials Prohibition",
  "Hazardous Materials Prohibition Description",
  "Signage Rights & Restrictions",
  "Signage Approval Required",
  "Signage Responsibility",
  "Signage Responsibility Description",
  "Events of Default - Tenant",
  "Cure Period for Tenant Default (days)",
  "Force Majeure Clause Summary",
  "Notice Address - Tenant",
  "Notice Method (Email/Registered Mail)",
  "Operating Expense Statement Frequency (Reconcilation statement)",
  "Financial Statements Required (Y/N)",
  "Financial Statements Required timeline",
  "Financial Statements Required Description",
  "Audit Rights",
  "Access for Inspections (notice required?)",
  "Surrender Conditions",
  "Holdover Rent Rate (if tenant holds over)",
  "Holdover Period Treatment",
  "Access Hours to Premises",
  "Landlord Right to Access",
  "Environmental Indemnity Terms",
  "Sustainability / ESG Obligations",
  "Energy Performance Required (Y/N)",
  "Energy Efficiency requirements",
  "Building Services Hours (HVAC/Lighting)",
  "Parking allocated area",
  "Parking allocated area description",
  "Parking allocated area restriction",
  "Parking area Responsibility",
  "Parking area Responsibility Description",
  "Water Resposibility",
  "Water Resposibility Description"
];
